openapi: 3.0.0
info:
  title: Users by OpenAPI
  description: Project created to show how to use OpenAPI
  version: 1.0.1
servers:
  - url: 'http://localhost:8080'
paths:
  /users:
    get:
      operationId: getAllUsers
      responses:
        200:
          description: "Return All books"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /users/user/{username}:
    get:
      operationId: getOneUser
      parameters:
        - in: path
          name: username
          schema:
            type: string
      responses:
        200:
          description: "Return user by name"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/addNewUser:
    post:
      operationId: addOneUser
      parameters:
        - in: query
          name: user
          schema:
            $ref: '#/components/schemas/User'
      responses:
        200:
          description: "Add new user"
          content:
            application/json:
              schema:
                type: string



components:
  schemas:
    SwaggerUser:
      type: object
      required:
        - _id
        - username
        - password
      properties:
        _id:
          type: string
        username:
          type: string
        password:
          type: string

  
